### ISSUE TITLE
Create order for products

### ISSUE THREAD

**Issue by parsipixel** [laravel/cashier#200]
Is there any way in this package to create orders for a product?

**Comment by GrahamCampbell** [comment]
Yes, just use the actual strip sdk.

**Comment by GrahamCampbell** [comment]
Otherwise, no, this package is designed to deal with subscriptions.

**Comment by JeremyHargis** [comment]
@GrahamCampbell When you say "Yes" in your first comment, do you mean "Yes, there is a way this package can create orders for a product?" (since that was the original question of this thread) or do you mean "No, you should instead use the Stripe SDK?". If the former, I would like to know how this works. Thanks.
