### ISSUE TITLE
payment without any plan

### ISSUE THREAD

**Issue by waqasraza123** [laravel/cashier#233]
There should be a way to accpet credit card payment without any plan. Like if user buy something charge for it, no need for any plan. @taylorotwell

**Comment by GrahamCampbell** [comment]
Probably just use stripe's package directly then?

**Comment by waqasraza123** [comment]
is there any plugin for laravel which does that? or any other plugin which can help me get credit card payments in laravel?

**Comment by jasonlewis** [comment]
Use the [`charge`](https://github.com/laravel/cashier/blob/5.0/src/Laravel/Cashier/Billable.php#L45) method, no subscription required.

**Comment by waqasraza123** [comment]
for that also we have to first assign a package to user. no? @jasonlewis

**Comment by jasonlewis** [comment]
@waqasraza123 nope, it's just a one off payment. It's mentioned in the docs: http://laravel.com/docs/5.1/billing#single-charges

It does say "against a subscribed user", however, because you can pass the *source* in the array of options you just need to get a token from Stripe or pass in the credit card details as the *source* and it'll charge the card accordingly.

**Comment by waqasraza123** [comment]
oh i was first awarding a plan to user then using charge method, i will try this. or if you have done it, it would be great if you can share the some code. @jasonlewis Thanks anyways
