### ISSUE TITLE
Unique-usage coupon code with newSubscription when the Stripe customer also doesn't exist is invalid

### ISSUE THREAD

**Issue by MacPrawn** [laravel/cashier#314]
So it seems that if you have a coupon code that can only be redeemed once, and you use it on a new subscription, on a Stripe customer that does not yet exist, the coupon code is sent once with the customer creation, and then once again with the subscription payload... And since the coupon is only valid once, Stripe fails to create the subscription because the coupon code has already been used, or burnt.

I think the SubscriptionBuilder's getStripeCustomer function should clear the coupon attribute after it creates the Stripe customer? (line 197)

Thanks!

**Comment by gwlortscher** [comment]
I can confirm this is a real bug; results in duplicate application of the coupon (once upon creation of the customer and once on creation of the subscription).

**Comment by luoshiben** [comment]
Also confirmed and has been a problem since commit [428f24b](https://github.com/laravel/cashier/commit/428f24b0b20b45201f45ff9976e3ba2c3934a468#diff-b3918af17708c2963637a574c9006260). The problem is that when a subscription is created for a model (user) that hasn't yet been registered as a Stripe customer, the coupon is tied to both the customer AND the subscription. This may not be a problem when the Stripe coupon is meant to be used repeatedly. However, when the coupon is set to be used once, this bug results in the user receiving the coupon discount twice.

An example to reproduce the problem:
```php
$user = BillableUser::create([ 'first' => 'Taylor', 'last' => 'Otwell']);
$user->newSubscription($subscription, $plan)->with($coupon);
```

I think maybe the solution is to not apply coupons that are set on the SubscriptionBuilder (via with($coupon)) to the owner entity when being registered with Stripe. Unless there are scenarios where coupons need to be applied to a user account (anyone know?), it seems like only applying them to the subscription is a more logical approach, especially since the with($coupon) method is on the SubscriptionBuilder (not a Stripe Customer object). If needed, a coupon may still be attached to a new Stripe customer by first explicitly using the Billable@createAsStripeCustomer method and passing in the coupon as one of the options. See [PR#350](https://github.com/laravel/cashier/pull/350).
