### ISSUE TITLE
Error: Call to undefined function Laravel\Cashier\config()

### ISSUE THREAD

**Issue by rossjcooper** [laravel/cashier#330]
I have forked this package and run the tests but I am getting the following error:

```
1) CashierTest::testSubscriptionsCanBeCreated
Error: Call to undefined function Laravel\Cashier\config()

/Users/Ross/Sites/laravel/packages/rossjcooper/cashier/src/Subscription.php:48
/Users/Ross/Sites/laravel/packages/rossjcooper/cashier/vendor/illuminate/database/Eloquent/Model.php:2685
/Users/Ross/Sites/laravel/packages/rossjcooper/cashier/vendor/illuminate/database/Eloquent/Model.php:2658
/Users/Ross/Sites/laravel/packages/rossjcooper/cashier/vendor/illuminate/database/Eloquent/Model.php:2602
/Users/Ross/Sites/laravel/packages/rossjcooper/cashier/vendor/illuminate/database/Eloquent/Model.php:3418
/Users/Ross/Sites/laravel/packages/rossjcooper/cashier/src/Subscription.php:345
/Users/Ross/Sites/laravel/packages/rossjcooper/cashier/src/Subscription.php:256
/Users/Ross/Sites/laravel/packages/rossjcooper/cashier/tests/CashierTest.php:88
```

I have tried running `composer update` but this makes no difference, any ideas?

**Comment by Repox** [comment]
This is caused by the configuration engine trying to utilize a Laravel helper as the alternative for the environment variable.

You can add the following to your `.env` file and your tests should go through:

    STRIPE_MODEL=User

**Comment by rossjcooper** [comment]
Ok thanks I'll give it a try

**Comment by SwiTool** [comment]
@Repox Could you elaborate ? How a var in the .env file could make the error disappear ?

**Comment by Repox** [comment]
@SwiTool Sure.

It's because of the following line of code: 
https://github.com/laravel/cashier/blob/7a549d0fb3b3a0a9236173f41f50a4172da6a59b/src/Subscription.php#L56

It checks whether or not the environment variable is defined and if not, the function `config` is used.

In this case, `config` is a helper function inside the Laravel Framework and isn't shipped with this repository, so that function will fail. This could probably be solved otherwise, but I get why we would like this to work with Laravel.

By setting the environment variable, everything works fine, though.

**Comment by SwiTool** [comment]
@Repox thanks.
