### ISSUE TITLE
[BUG] deleteCards() does not delete card details from user table

### ISSUE THREAD

**Issue by Mr-Anonymous** [laravel/cashier#370]
When I delete user's card using the `deleteCard()` method, it does not delete the card info in user table.

```
$user->deleteCards();
```

The above deletes the `default_source` in Stripe but the user table still shows `card_brand` and `card_last_four`.

**Comment by JorgenVatle** [comment]
Just encountered this myself. (Cashier 7.0)

As this issue is on top of Google search results, I might as well pitch in.

I'm not entirely sure if it is intentional that your user's card details aren't removed automatically when running `deleteCards()` method. But running `updateCardFromStripe()` will synchronize your user's saved card details with Stripe. Essentially, removing their saved card details from your table.

The Billable `deleteCards()` method is quite simple:
```php
    /**
     * Deletes the entity's cards.
     *
     * @return void
     */
    public function deleteCards()
    {
        $this->cards()->each(function ($card) {
            $card->delete();
        });
    }
```
So you could just override the method in your User model with something like this, which will automatically syncronize your user's card details with Stripe.
```php
    /**
     * Deletes the entity's cards.
     *
     * @return void
     */
    public function deleteCards()
    {
        $this->cards()->each(function ($card) {
            $card->delete();
        });
        
        $this->updateCardFromStripe();
    }
```

**Comment by driesvints** [comment]
Should be fixed now.
