### ISSUE TITLE
Error when i create Invoice : "Nothing to invoice for customer"

### ISSUE THREAD

**Issue by lemattou** [laravel/cashier#405]
Hello,

Without changing my code, i have a new error about Invoices.

This is my code : 

```
\Stripe\Stripe::setApiKey(env('STRIPE_SECRET'));
            
$charge = \Stripe\Charge::create(array(
                "amount" => $product_price,
                "currency" => "EUR",
                "customer" => $customer->id,
                "description" => $product_name,
                "email" => $customer->email
            ));
$r = Auth::user()->invoice()
```

And the response is : "Nothing to invoice for customer"

Sorry for my english i'm french :)
Thanks !

**Comment by Mr-Anonymous** [comment]
Did you find an answer to this error message you were getting?

**Comment by cohom** [comment]
I wonder anyone could ever manually create an invoice according to the example [https://stripe.com/docs/api#create_invoice](url). My code is almost identical:

```
            $invoice = \Stripe\Invoice::create([
                "customer" => $this->customer,
            ]);
```

Yet this hasn't ever worked whenever the customer id is included in the parameter; more precisely, in my application log, the exception message is shown as:

> Stripe\Error\InvalidRequest: Nothing to invoice for customer (uncaught exception) at vendor/stripe/stripe-php/lib/ApiRequestor.php line 110 {"exception":"[object] (Stripe\\Error\\InvalidRequest(code: 0)

Since I want to pay off every added invoice items right away, this is crucial issue for me.
Any idea?

**Comment by henry-stripe** [comment]
The "Nothing to invoice for customer" error happens when you try to [create an Invoice](https://stripe.com/docs/api#create_invoice) but there are no InvoiceItems to charge. You can [request a list of invoice items](https://stripe.com/docs/api#list_invoiceitems) by running `\Stripe\InvoiceItem::all();`. 

Rather than doing 2 round trips to Stripe's servers, you could handle the error in your code. If you do this, your users won't receive any confusing notifications about an empty invoice. 

If you have any other issues with this, [send a message to Stripe's support team](https://support.stripe.com/email/login) directly.

**Comment by rakeshbhandarkar1987** [comment]
@henry-stripe 
Still facing this issue though I am already having "InvoiceItems" to charge.
Can you please give details when "Nothing to invoice for customer" exception thrown:

**Comment by henry-stripe** [comment]
@rakeshbhandarkar1987

If you have any invoice items, you shouldn't be getting this error. To best debug this issue, it would help to have [the Invoice ID](https://stripe.com/docs/api#invoice_object-id) (`in_XXXX`). Because this is specific to your particular account, could you write in to [our support](https://support.stripe.com/email/login)

**Comment by rakeshbhandarkar1987** [comment]
@henry-stripe 
Thanks for your inputs. But problem is still not solved for me.
Before creating invoice I fetched InvoiceItems using below code snippet. 
```
InvoiceItem.list(new HashMap<String, Object>()).each {item ->
                System.out.println(item)
            }
```
Since I am getting InvoiceItems in response so I can say that invoice items are there before creating invoice.

Using below snippet for creating invoice:
`Invoice.create(invoiceParams)`

In `invoiceParams` I am passing only customerId.

Please let me know if you can help me. Otherwise as suggested I will raise a support ticket for the same.

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.

**Comment by ankitcodefarm** [comment]
Hello, I am facing the same issue while updating the subscription first time.
Subscription add is working fine but whenever I want to update the subscription with the higher amount of subscription it will give this error, but in the backside, it will already get updated. if I will go back and refresh it will show that I have successfully updated the subscription. 

       // If Invoice is not generated
        try {  
                 $invoicedata = $stripe->invoices()->create($subscription->user->stripe_customer_id); 
        } catch (Exception $e) {
            // If Invoice is generated 
            $invoices = $stripe->invoices()->all(['customer' => $subscription->user->stripe_customer_id, 'limit' => 1]);
            $invoicedata = $invoices['data'][0];
        }

it will work fine in localhost, this issue came on live server. Currentely the applicaion is on development mode. And it will heppen only once then it will work fine. I am implimenting this for first time. 
am i doing someting wrong?

**Comment by Folling** [comment]
Just to add to this topic, having investigated what stripe sends when you create an invoice in the interface, it seems the `pending_invoice_items_behavior` parameter can be set to `exclude` to create an empty draft invoice which you can append invoice items to at a later point in time.

**Comment by COil** [comment]
For followers. We also had this error. A for loop for supposed to add invoice items, but for some reason, there wasn't any data. Therefore, it was tried to create the invoice without invoice items, which raises this stripe error.

**Comment by vimalpcv** [comment]
set `pending_invoice_items_behavior` parameter to `exclude` on the `stripe.Invoice.create `

**Comment by CodeWithOz** [comment]
> Just to add to this topic, having investigated what stripe sends when you create an invoice in the interface, it seems the `pending_invoice_items_behavior` parameter can be set to `exclude` to create an empty draft invoice which you can append invoice items to at a later point in time.

What's strange about this is that stripe's [`Invoice.create` docs](https://stripe.com/docs/api/invoices/create#create_invoice-pending_invoice_items_behavior) state clearly that the default behavior is `exclude` (emphasis added by me):
> How to handle pending invoice items on invoice creation. One of `include` or `exclude`. `include` will include any pending invoice items, and will create an empty draft invoice if no pending invoice items exist. `exclude` will always create an empty invoice draft regardless if there are pending invoice items or not. **Defaults to `exclude` if the parameter is omitted.**

**Comment by ZaidPathan** [comment]
`pending_invoice_items_behavior` value to `exclude` worked well for `collection_method` `charge_automatically` and `auto_advance` `true`.

Step 1: `stripe.invoices.create`
Step 2: `stripe.invoiceItems.create` with above `invoice.id`
Step 3: `stripe.invoices.finalizeInvoice`

**Comment by najathi** [comment]
Add pending_invoice_items_behavior parameter to exclude on the Stripe\Invoice::create

```
$invoice = Stripe\Invoice::create([
            'customer' => $customer['id'],
            'description' => "Thank you for your business.",
            "collection_method" => "send_invoice",
            "days_until_due" => 30,
            'custom_fields' => [
                ['name' => 'VAT', 'value' => 'xxxxxxxxx'],
            ],
            **'pending_invoice_items_behavior' => "exclude",**
            'currency' => 'gbp',
]);
```
