### ISSUE TITLE
[Documentation] metadata attribute with charge() and invoiceFor()

### ISSUE THREAD

**Issue by FPGL** [laravel/cashier#421]
Hi,

The metadata attribute is missing in the documentation. 
In https://laravel.com/docs/5.4/billing. 
Charge With Invoice is described as :
```
$user->invoiceFor('One Time Fee', 500, [
    'custom-option' => $value,
]);
```

Could be :
```
$user->invoiceFor('One Time Fee', 500, [
    'metadata' => [
        'custom-option' => $value,
    ]
]);
```

**Comment by sdebacker** [comment]
The metadata is set to a line of the invoice and not on the invoice itself. Is it the intended behavior ?

**Comment by driesvints** [comment]
@FPGL This is actually correctly described because it just simple allows you to pass any option you want for the api call. You *could* add a metadata key but also add a bunch of other options which the Stripe API allows.

@sdebacker `invoiceFor` indeed calls the `tab` method which just adds an invoice line.
