### ISSUE TITLE
How to Resume subscription after fully expired?

### ISSUE THREAD

**Issue by sagar-mi** [laravel/cashier#462]
@MichaelHoughton  As per doc - "If a user has cancelled their subscription and you wish to resume it, use the resume method. The user must still be on their grace period in order to resume a subscription"

**Comment by inxilpro** [comment]
You have to start a new one.

**Comment by sagar-mi** [comment]
But if  User is in trial Period and if they cancel subscription and resume again than trial will be lost?

**Comment by MichaelHoughton** [comment]
@sagar-mi - if they are still within their trial period, they will be in the grace period, so the subscription can be renewed with:

```php
$user->subscription('main')->resume();
```

Refer to `Resuming Subscriptions` in the docs - https://laravel.com/docs/5.5/billing

**Comment by sagar-mi** [comment]
@MichaelHoughton As per doc - "If the user cancels a subscription and then resumes that subscription before the subscription has fully expired, they will not be billed immediately"  But when i use resume method before fully expire than trial period lost means its directly charge to user instead it should charge when trial period will be over.

**Comment by driesvints** [comment]
From the `cancel` method:

```php
        // If the user was on trial, we will set the grace period to end when the trial
        // would have ended. Otherwise, we'll retrieve the end of the billing period
        // period and make that the end of the grace period for this current user.
        if ($this->onTrial()) {
            $this->ends_at = $this->trial_ends_at;
        } else {
            $this->ends_at = Carbon::createFromTimestamp(
                $subscription->current_period_end
            );
        }
```

So if the user cancels within its trial, the grace period will end after the trial. If he then resumes during this the trial will be kept on the subscription.

If the user instead cancels their subscription it will continue to run until its billing period ends. If after that the user resumes its subscription during the grace period, the trial will be reset and end immediately (since it was already over anyway probably).
