### ISSUE TITLE
Subscribe twice

### ISSUE THREAD

**Issue by pjebs** [laravel/cashier#473]
```
$billing->newSubscription('main', 'plan')->create('tok_visa', [
    		'email' => $customer->email,
		]);
```

It appears that if you call this twice, you can subscribe to the _same_ plan twice.
On stripes platform, the customer is considered the same, but on laravel's database and on stripe, the subscription is registered twice.

Is this a bug?

**Comment by driesvints** [comment]
Hey yes, it's perfectly possible to have two subscriptions to the same plan. You'll need to use the checks to see if you are already subscribed to a plan before trying the same thing again: https://laravel.com/docs/5.7/billing#checking-subscription-status

**Comment by radic4** [comment]
Hey all,

I have same problem and partially solved this with @driesvints suggestion.

Currently, if i subscribed to plan i can't subscribe to it again.

The problem is when i am not yet subscribed and call my API URL for subscription multiple times at same time it buys multiple subscriptions. The problem is that if statement return false for all requests because first request is not yet finished and user is not yet subscribed.

Is there any chance i can prevent user calling URL multiple times at same time? Or somehow wait for one request to finish and then execute second etc.
