### ISSUE TITLE
only 10 invoice items shown

### ISSUE THREAD

**Issue by maxx1337** [laravel/cashier#476]
If you have many invoice items, only the first 10 items will be shown on the invoice.

Stripe imitates the requests to 10 by default and offer pagination
https://stripe.com/docs/api#pagination

my workaround currently is this:
`if ($stripeInvoice->lines->has_more){`
`    $stripeInvoice->lines = $stripeInvoice->lines->all(['limit' => 100]);`
`}`
and pass then the $stripeInvoice to the Laravel\Cashier\Invoice constructor

**Comment by rental-ninja** [comment]
Hi!
We are facing the same issue since many months ago. Some of our invoices have many lines and due to the fact that the findInvoice method only retrieves the invoice without all the lines, we are missing many lines in our invoices.
We tried to develop a solution without modifying neither the Cashier nor Spark, so we can keep our dependencies updated automatically. We could modify the invoice when a user is trying to download it, but the problem comes when we want to modify the notification (email) that Spark sends to the user when the subscription is modified (or just charged the normal subscription). We can't replace the notification nor the Controllers.
We will do a pull request to try to solve this issue as we need to get our invoices right for our customers. Thanks for the suggestion @maxx1337

**Comment by driesvints** [comment]
PR is merged now so should be fixed in the latest release.

**Comment by rental-ninja** [comment]
Great thanks a lot!

**Comment by jimiero** [comment]
This is what I did, and seems to be working just fine:

`$items = auth()->user()->invoices();
        $total = $items->count(); // Specify your total here

        $perPage = 10;

        $currentPage = LengthAwarePaginator::resolveCurrentPage();
        
        $currentItems = $items->slice(($currentPage - 1) * $perPage, $perPage)->values();

        $invoices = new LengthAwarePaginator(
            $currentItems, // The items for the current page
            $total,        // Total number of items
            $perPage,      // Items per page
            $currentPage,  // Current page number
            ['path' => LengthAwarePaginator::resolveCurrentPath()] // Path to append to pagination links
        );

        $invoices->appends(request()->query());`
