### ISSUE TITLE
Billing Subscription Name

### ISSUE THREAD

**Issue by mavinothkumar** [laravel/cashier#478]
Hi

Can anyone please suggest me how to get the billing subscription name here (invoice object),

or Subscription name in subscription table?

````
<table>
    @foreach ($invoices as $invoice)
        <tr>
            **<td>BILLING SUBSCRIPTION NAME ??</td>**
            <td>{{ $invoice->date()->toFormattedDateString() }}</td>
            <td>{{ $invoice->total() }}</td>
            <td><a href="/user/invoice/{{ $invoice->id }}">Download</a></td>
        </tr>
    @endforeach
</table>
````

**Comment by driesvints** [comment]
Hey @mavinothkumar. This is hard to determine from an invoice because you could be invoiced for multiple subscriptions at the same time I believe. 

Anyway, looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs or problems. If you have a question on how to use functionality provided by this repo you can try one of the following websites:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
