### ISSUE TITLE
isInTestingEnvironment function is not working with php artisan config:cache

### ISSUE THREAD

**Issue by ivankolodii** [laravel/cashier#537]
```php
protected function isInTestingEnvironment()
{
        return getenv('CASHIER_ENV') === 'testing';
}
```
If you use `php artisan config:cache` this function will always return null according to [https://laravel.com/docs/5.6/configuration#configuration-caching](docs).

Config file should be created and used via `config('cashier.env')`

P.S. Still don't understand purpose of this function. Value `testing` should be used on production too.

**Comment by driesvints** [comment]
I cannot see why you would use `testing` in production. Your production environment is for live keys only. This method shouldn't be used in combination with caching your config.

**Comment by ivankolodii** [comment]
Stripe Webhook controller is using that method.

```
public function handleWebhook(Request $request)
    {
        $payload = json_decode($request->getContent(), true);

        if (! $this->isInTestingEnvironment() && ! $this->eventExistsOnStripe($payload['id'])) {
            return;
        }

        $method = 'handle'.studly_case(str_replace('.', '_', $payload['type']));

        if (method_exists($this, $method)) {
            return $this->{$method}($payload);
        } else {
            return $this->missingMethod();
        }
    }
```

**Comment by driesvints** [comment]
@ivankolodii ah sorry, gotcha. But the same remark stands. On production this will simply default to false.

**Comment by fbingha** [comment]
You should fix this since caching configuration is a valid option in a testing environment.

There is an issue on Windows Apache when using multiple projects under the same server. When one project is calling the api of a second project, the configuration of one project is read by the second project. Since the standard line to resolve this is "cache your config" then you should fix the problem here so I don't have to overwrite isInTestingEnvironment to not use getenv. 

"To clear things up; this is a known issue. It's just not documented.

You must run php artisan config:cache in both Laravel projects to generate a cached configuration. This is a requirement for Apache on Windows (and many other setups)."


https://github.com/laravel/framework/issues/19990
https://github.com/laravel/framework/issues/21533
https://github.com/laravel/framework/issues/20207
https://github.com/laravel/framework/issues/19454
https://github.com/laravel/framework/issues/13906
https://github.com/laravel/framework/issues/8191

If you attended Laracon 2018 then surely you hear when Taylor said top not call getenv() in your code.

**Comment by driesvints** [comment]
Heya @fbingha. Thanks for bringing this to my attention. I'll re-open this to have another look at a later time. In the meantime feel free to send in a PR which might be able to fix this.

**Comment by driesvints** [comment]
I've sent in a proposal which refactors the way we tackle this problem. Please have a look and let me know what you think: https://github.com/laravel/cashier/pull/591

**Comment by driesvints** [comment]
The behavior for this has been changed in 9.0 which will be released soon. An upgrade guide will be provided.
