### ISSUE TITLE
How can I add trial days to an existing subscription?

### ISSUE THREAD

**Issue by jose46moreno** [laravel/cashier#550]
I want to add trial days after I create a subscription, so that the first payment is made when I create it and the next payment when the trial days are over.

Any ideas?

**Comment by jose46moreno** [comment]
Ok, it is on grace period.

**Comment by kgenly** [comment]
My approach would be to create the subscription with trial, then perform a one-off charge for whatever the start fee is.

**Comment by driesvints** [comment]
At the moment there's no functionality that adds trial days to an existing subscription. The Stripe docs detail that this is possible but will result in a proration (which seems obvious): https://stripe.com/docs/billing/subscriptions/changing

I can see this being useful in some cases so I'll tag this as a feature request. Since this is nothing we'll use ourselves at anytime soon we'll probably won't develop this ourselves. We are however welcoming PRs for this.

**Comment by mikkelbfriis** [comment]
@driesvints Couldn't you just update it through the Stripe API manually (not using cashier, but sending the data throuh metadata)
and then updating your user's subscription? (trial_ends_at and ends_at)?

**Comment by driesvints** [comment]
@mikkelbfriis not sure. Would have to dig into the api and don't have the time for that atm.

**Comment by driesvints** [comment]
I've sent in a PR for this here: https://github.com/laravel/cashier/issues/550
