### ISSUE TITLE
[Request] Add an option for non-prorated plan swaps to send an invoice or not

### ISSUE THREAD

**Issue by stijnfrishert** [laravel/cashier#557]
When I change a plan and set proration to false, the user is automatically invoiced. Is it possible to add an argument to this function (or otherwise add functionality to the Subscription class) that makes the invoice optional?

**Comment by driesvints** [comment]
Hey @stijnfrishert. The way I see it, when a plan swap happens, the user should *always* be invoiced because you'd want to bill any changes to the plan amount immediately. So for the `swap` method I don't see how adding a flag to disable the invoicing for a billable entity could be of help. 

If you however, just want to update the prorate setting of a subscription, you could use the `updateQuantity` method to do this: https://laravel.com/docs/5.7/billing#subscription-quantity

```php
$user->subscription('main')->noProrate()->updateQuantity(1);
```

Hope this helps.

**Comment by yougotnet** [comment]
The problem with the noProrate option is that when you execute a swap right afterwards you can't turn on Prorate.

If I have a user downgrade the plan, I do not want to prorate or give a refund, but if the user downgrades and then upgrades higher to what the originally paid during the subscription period, then I want to swap to the original plan with noProrate and then swap to a higher plan with a Prorate.

What I did to fix the issue on my end is add a new function to the Subscription model called Prorate() so that I can turn the $prorate flag to true.  If you would simply add the function to the base code it would help a lot of developers out.
