### ISSUE TITLE
Subscription cancels after swap with skipTrail

### ISSUE THREAD

**Issue by Dasinfomedia2** [laravel/cashier#585]
I have plan with $0 with 30 trail days and 2nd plan with $15 with 0 trail days.

So when i am upgrading plan to $15 from 0 it cancels the subscription after collecting payment.

I ask for card details when they try to upgrade plan.

When they 1st sign up with $0 plan i dont ask for card details i create subscription directly without stripetoken.

**Comment by driesvints** [comment]
@Dasinfomedia2 Did you use the `updateCard` method on the billable user after updating his card details before you swap plans? If you attempt to swap plans when a customer doesn't has a payment source yet then it's normal that his subscription will get cancelled immediately.

Also: what version of Cashier are you running? A bug fix was released 5 days ago with a fix for swapping plans but not sure if that has anything to do with your issue.

**Comment by Dasinfomedia2** [comment]
Yes, I did use the update card method. 
My version is 7.1

**Comment by driesvints** [comment]
I'll need more info and/or code to debug this further. Please post relevant code like models, jobs, commands, notifications, events, listeners, controller methods, routes, etc. You may use https://paste.laravel.io to post larger snippets or just reply with shorter code snippets. Thanks!

**Comment by Dasinfomedia2** [comment]
Yes sure, Here it is as below. Thank you.

$plan_id = $request->planId;
$currentPlanId = $request->currentPlanId;
$stripeToken = $request->stripeToken;
		
$user = User::find(Auth::user()->id);
if($stripeToken != null)
{
	$cardDetailUpdate = $user->updateCard($stripeToken);
}

$stripePlanChange = $user->subscription($subscriptionsOldData->name)->skipTrial()->swap($plan->stripe_plan_id);

**Comment by Dasinfomedia2** [comment]
If i remove skipTrial() then it works but trial days carried forward to new plan.

**Comment by driesvints** [comment]
The problem is probably that if doesn't passes the `$stripeToken` check and that you start the subscription without a payment source. That's why the subscription gets cancelled immediately.

Anyway, I believe you just have some things wrongly set up but this is more of a question for a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)

Good luck!
