### ISSUE TITLE
[Proposal] add updateSource method

### ISSUE THREAD

**Issue by vladflip** [laravel/cashier#656]
Current `updateCard` method creates a new card and leaves the old one intact. This was discussed in #282, but wasn't solved.

Having the new `updateStripeCustomer` method from #634, I would like to suggest creating an `updateSource` method or changing the way `updateCard` method works.

Stripe encourages using this way of updating a card:
https://stripe.com/docs/api/customers/update#update_customer-source
https://stripe.com/docs/recipes/updating-customer-cards#using-the-token-to-update-the-customers-card

Following the [contribution guidelines](https://github.com/laravel/cashier/blob/9.0/contributing.md), I created this issue before creating a pull request, however the implementation of the `updateSource` method is ready and you can check it [here](https://github.com/vladflip/cashier/commit/7eb0585ae173e88fe0497509d8e8805c880b3bd2). I'm waiting for your review before I can make a pull request.

**Comment by driesvints** [comment]
I'm going to have to say no because it's basically a one-liner which you can add to your own project. The current Stripe docs are also all disregarding making use of the current cards api because of the new SCA regulations coming up in September. We'll need to review all of this for v10 so I'm gonna hold off on this now.

**Comment by driesvints** [comment]
Btw also see: https://github.com/laravel/cashier/issues/649
