### ISSUE TITLE
Proposal: Improve Charge handling

### ISSUE THREAD

**Issue by DanielDarrenJones** [laravel/cashier#686]
Hi, 

I have been working on a site recently which does a bit of work with stripe charges along side the subscription management, during this process I extracted a new package called cashier extended to improve some of the functionality around charges and to help make the work around charges easier.

As there are quite a few breaking changes coming in v10 I would like to propose to pull some or all of this into the core? the current work I have done is available to see here: https://github.com/steadfast-collective/cashier-extended (it's not finished yet and will likely need a few tweaks for the SCA changes coming)

If this is something you would consider helpful I would be happy to make a PR for this.

Would appreciate if you could take a look @driesvints and let me know :)

Thanks
Dan

**Comment by driesvints** [comment]
@DanielDarrenJones hmm, I don't think we'll ever add in functionality to keep track of charges in your own DB since all of the data is easily retrieved with the Stripe API. I also suspect that this will conflict a lot with the Payment Intens API I'm working on: https://github.com/laravel/cashier/pull/667

What is it that you exactly are trying to solve? Can you add some more background info on the ideas behind the package and real-life use cases? Thanks!

**Comment by DanielDarrenJones** [comment]
@driesvints Thanks for getting back so fast.

Basically my use case would be things like a single one time purchase upgrade and checking if they have made that purchase. Or it could be used for more advanced features for example selling products.

I created this package when I was working on an agency project where the customer wanted to sell a subscription, but also have a one time upgrade fee. While I could have worked directly with the Stripe API I didn't want to query this every time and settled on following the same pattern as Cashier currently does, creating a local version of the sale and ensuring it is kept up to date with webhooks, this was nice on two fronts: performance was much better and additionally it gave quick scaffolding for doing some simple analytics.

When I was working this through I settled on the below DB format:

```php
Schema::create('charges', function ($table) {
    $table->bigIncrements('id');
    $table->unsignedBigInteger('user_id');
    $table->string('name');
    $table->string('stripe_id')->collation('utf8mb4_bin');
    $table->integer('amount');
    $table->integer('amount_refunded');
    $table->string('currency');
    $table->timestamp('paid_at')->nullable();
    $table->timestamps();
});
```

I'm not entirely sure the argument of it being easily retrieved from the stripe API is fair as the same could be said about the subscriptions, this is basically doing the same thing and just making the rest of the stripe functionality nicer to use in laravel for a majority of people.

I agree it is very likely to conflict with the payment intents API you are currently working on, and this thread is just to test the water of the concept, if you were happy for me to submit a PR I would make all of the necessary changes to ensure it meets the new SCA requirements.

Im also fully aware that the current package doesn't have tests, and this is something I would rectify in the PR.

This is something i'd really like to flesh out and put some proper work into and i'd be happy to jump into a call to discuss it more :)

Thanks!

**Comment by driesvints** [comment]
I have to be fair with you. I don't think we'll be implementing this any time soon. Cashier is in the first place meant for subscription based billing and the single charges is just a small addition which made its way into the package. 

I see you talking about performance but you can also achieve that with caching. I know the subscriptions could be handled in the same way but cashier was first developed as a hybrid of braintree and stripe and thus we needed a universal way to handle subscriptions so a database table made sense. Also because it's the fastest way to handle the data. 

I feel like this is something not a lot of people will need, that's why a package like yours makes sense. If we merged it into the Cashier core we're stuck with maintaining it. 

So I'm sorry but we're not going to implement this. Wishing you much luck with your package. Definitely try to adopt the new payment intents API to handle the SCA stuff.
