### ISSUE TITLE
Send ConfirmPayment after invoice.payment_failed webhook also?

### ISSUE THREAD

**Issue by ralphmorris** [laravel/cashier#808]
Not sure if this is correct but I recently upgraded with the new V10 for SCA updates. As  part of doing so I thought I could remove my my webhook method handleInvoicePaymentFailed() which used to send an email asking the user to update their billing info as the ConfirmPayment notification was going to replace this. (When testing I noticed both notifications were being sent after a failed payment which I obviously didn't want.)

I now realise that ConfirmPayment won't get triggered unless it is for SCA reasons, and not every time a payment fails. Whoops!

However, when checking on a user who's payment has failed (but not due to SCA) I noticed that their stripe_status is now set to past_due and they have the alert prompting them to complete an incomplete payment as per the new user flow which makes me wonder why we can't also send the ConfirmPayment (or similar) notification for the invoice.payment_failed webhook?

I'm curious to know how others handle their payment failed notifications for both SCA and when the reason is not SCA, such as insufficient_funds.

Thanks!

**Comment by driesvints** [comment]
Heya, thanks for your suggestion. The webhook for `handleInvoicePaymentActionRequired` was indeed specifically added for SCA reasons. We could consider making it more generic indeed so it's more applicable for other use cases or just add a second one for failed payments.

We only need to test this very thoroughly so the two don't conflict with each other and we don't send duplicate emails. This will also need to work properly with payment intents because the payment page needs a payment intents identifier. 

This would also need to go to the master branch for the next version. Before you start working on this: I'll need to check with Taylor what we can do.

**Comment by driesvints** [comment]
I've looked into this but unfortunately I believe there's no way to know when to know if both events are sent or not. If you can figure out a way to know for sure that the customer won't get duplicate notifications we can reconsider this.
