### ISSUE TITLE
Save Stripe responses in attributes

### ISSUE THREAD

**Issue by pierrocknroll** [laravel/cashier#820]
Hello,
I'm wondering if it would be a good idea to avoid some calls to Stripe's API in order to speed up Cashier.
When asStripeCustomer(), asStripeSubscription(), etc... methods are called several times, Stripe is called each time, wouldn't it be a good idea to save the first return in an attribute?

Something like : 
```php
    /**
     * @var \Stripe\Customer
     */
    private $stripeCustomer;

    /**
     * Get the Stripe customer for the model.
     *
     * @return \Stripe\Customer
     */
    public function asStripeCustomer()
    {
        if (!isset($this->stripeCustomer)) {
            $this->stripeCustomer = StripeCustomer::retrieve($this->stripe_id, $this->stripeOptions());
        }
        return $this->stripeCustomer;
    }
```
@driesvints ?

Thanks

**Comment by driesvints** [comment]
I think this has been asked before iirc. The problem with keeping the original response in memory is that during the process, these responses can get out of date because of actions taken within Stripe and thus it could lead to inconsistent data from the actual state within Stripe. So I personally think this isn't the ideal solution. If we can speed up Cashier by making less API calls, all for the better but I believe there aren't many opportunities to do so atm. But feel free to prove me wrong by sending in a PR :)

Thanks.
