### ISSUE TITLE
paymentMethods() return always empty object result 

### ISSUE THREAD

**Issue by hiren-ghodasara** [laravel/cashier#821]
- Cashier Version: ^10.5
- Laravel Version: ^6.0
- PHP Version:  7.3.5
- Database Driver & Version:

### Description:
paymentMethods() retrieve always array with empty object. 
```
public function userAllPaymentMethods(Request $request)
    {
        $user = User::find(5);
        $paymentMethod = $user->paymentMethods();
        return response($paymentMethod);
    }
```
Result : 
https://www.screencast.com/t/aqenaud77A

Also  using Stripe PaymentMethod lib it's works.
```
public function userAllPaymentMethods(Request $request)
    {
        $user = User::find(5);
        \Stripe\Stripe::setApiKey('{{KEY}}');
        $paymentMethod = \Stripe\PaymentMethod::all([
            'customer' =>  $user->stripe_id,
            'type' => 'card',
        ]);
        
        return response($paymentMethod);
    }
```
Result :  
https://www.screencast.com/t/X14ane7WyqS

stackoverflow : [Here](https://stackoverflow.com/questions/58898278/laravel-cashier-paymentmethods-return-always-empty-object-result)

**Comment by driesvints** [comment]
Since we have several tests that verify that this works and your stackoverflow issue is only a day old I'm gonna ask if you can maybe try some other support channels first before trying the issue tracker here. If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
